version: "3.9"
services:
    web-api:
        image: ${DOCKER_REGISTRY}web-api
        ports:
            - "${WEB_API_PORT}:80"
            - "${WEB_API_PORT_HTTPS}:443"
        environment:
            - ASPNETCORE_ENVIRONMENT
            - ConnectionStrings__DefaultConnection
    vue-app:
        image: ${DOCKER_REGISTRY}vue-app
        depends_on:
            - web-api
        ports:
            - "${VUE_APP_PORT}:80"
            - "${VUE_APP_PORT_HTTPS}:443"
        environment:
            - NODE_ENV
            - VerticalSliceConfig__ApiEndpoint
    web-dotvvm:
        image: ${DOCKER_REGISTRY}web-dotvvm
        depends_on:
            - web-api
        ports:
            - "${WEB_DOTVVM_PORT}:80"
            - "${WEB_DOTVVM_PORT_HTTPS}:443"
        environment:
            - ASPNETCORE_ENVIRONMENT
            - VerticalSliceConfig__ApiEndpoint
