apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $DOCKER_HOST_NAME
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$3
spec:
  ingressClassName: nginx-default
  rules:
  - host: $DOCKER_HOST_NAME
    http:
      paths:
      - path: /(web-dotvvm)(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: web-dotvvm
            port:
              number: 80
      - path: /(vue-app)(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: vue-app
            port:
              number: 80
