name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: ./build.sh
      
    - name: Set login for Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push Docker Image
      run: |
        imageNamePrefix='kennethchoe'
        $imageNames = (`sed -n -e 's/^[ \t]*image: ${DOCKER_REGISTRY}//p' docker-compose.yml`)
        for imageName in "${imageNames[@]}"
        do
            docker tag $imageName "$imageNamePrefix$imageName"
            docker push "$imageNamePrefix$imageName"
        done
